version: "3.7"
services:
  vpn:
    build: .
    container_name: "wireguard"
    cap_add:
      - NET_ADMIN
    ports:
      - 51820:51820
    restart: always
    tty: true
    command: /bin/bash -c "/etc/wireguard/setup.sh && /bin/bash"
